version: "3.7"

services:

  postgres:
    image: postgis/postgis:14-3.2
    environment:
      POSTGRES_PASSWORD: insecure-postgres-kobo-dev
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      # Used to create two databases; see
      # https://github.com/docker-library/docs/tree/b56d2dd13bee760cb7a569969f0f7d0c71e1f637/postgres#initialization-scripts
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 10.6.7.6
    ports:
      - 10.6.7.1:60666:5432

  redis:
    image: redis
    volumes:
      - ./storage/redis:/data
    command: --requirepass insecure-redis-kobo-dev
    networks:
      default:
        ipv4_address: 10.6.7.7
    ports:
      - 10.6.7.1:60667:6379

  mongo:
    image: mongo:5.0.8
    environment:
      # HELLO: the root user only gets created in the `admin` database and
      # cannot authenticate to other databases like `formhub`
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: insecure-mongo-kobo-dev
      MONGO_INITDB_DATABASE: formhub
    volumes:
      - ./storage/mongo:/data/db
      # Used to grant access to `formhub` database by user `kobo`
      # with password `insecure-mongo-kobo-dev`
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 10.6.7.8
    ports:
      - 10.6.7.1:60668:27017

  kpi:
    image: kobotoolbox/kpi:2.023.04b
    env_file: envfile
    networks:
      default:
        ipv4_address: 10.6.7.9
    ports:
      - 10.6.7.1:8006:8006
    command: ['./manage.py', 'runserver', '0:8006']
    depends_on: ['postgres', 'redis', 'mongo']

  kobocat:
    image: kobotoolbox/kobocat:2.023.04
    env_file: envfile
    networks:
      default:
        ipv4_address: 10.6.7.10
    ports:
      - 10.6.7.1:8007:8007
    command: ['./manage.py', 'runserver', '0:8007']
    depends_on: ['postgres', 'redis', 'mongo']

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.6.7.0/24
